// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.18.1
// source: mcp.proto

package mcp

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	PdfProcessor_ExtractText_FullMethodName = "/mcp.PdfProcessor/ExtractText"
)

// PdfProcessorClient is the client API for PdfProcessor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PdfProcessorClient interface {
	// 流式上传PDF并返回解析文本
	ExtractText(ctx context.Context, opts ...grpc.CallOption) (PdfProcessor_ExtractTextClient, error)
}

type pdfProcessorClient struct {
	cc grpc.ClientConnInterface
}

func NewPdfProcessorClient(cc grpc.ClientConnInterface) PdfProcessorClient {
	return &pdfProcessorClient{cc}
}

func (c *pdfProcessorClient) ExtractText(ctx context.Context, opts ...grpc.CallOption) (PdfProcessor_ExtractTextClient, error) {
	stream, err := c.cc.NewStream(ctx, &PdfProcessor_ServiceDesc.Streams[0], PdfProcessor_ExtractText_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &pdfProcessorExtractTextClient{stream}
	return x, nil
}

type PdfProcessor_ExtractTextClient interface {
	Send(*PdfRequest) error
	CloseAndRecv() (*PdfResponse, error)
	grpc.ClientStream
}

type pdfProcessorExtractTextClient struct {
	grpc.ClientStream
}

func (x *pdfProcessorExtractTextClient) Send(m *PdfRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *pdfProcessorExtractTextClient) CloseAndRecv() (*PdfResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(PdfResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PdfProcessorServer is the server API for PdfProcessor service.
// All implementations must embed UnimplementedPdfProcessorServer
// for forward compatibility
type PdfProcessorServer interface {
	// 流式上传PDF并返回解析文本
	ExtractText(PdfProcessor_ExtractTextServer) error
	mustEmbedUnimplementedPdfProcessorServer()
}

// UnimplementedPdfProcessorServer must be embedded to have forward compatible implementations.
type UnimplementedPdfProcessorServer struct {
}

func (UnimplementedPdfProcessorServer) ExtractText(PdfProcessor_ExtractTextServer) error {
	return status.Errorf(codes.Unimplemented, "method ExtractText not implemented")
}
func (UnimplementedPdfProcessorServer) mustEmbedUnimplementedPdfProcessorServer() {}

// UnsafePdfProcessorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PdfProcessorServer will
// result in compilation errors.
type UnsafePdfProcessorServer interface {
	mustEmbedUnimplementedPdfProcessorServer()
}

func RegisterPdfProcessorServer(s grpc.ServiceRegistrar, srv PdfProcessorServer) {
	s.RegisterService(&PdfProcessor_ServiceDesc, srv)
}

func _PdfProcessor_ExtractText_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PdfProcessorServer).ExtractText(&pdfProcessorExtractTextServer{stream})
}

type PdfProcessor_ExtractTextServer interface {
	SendAndClose(*PdfResponse) error
	Recv() (*PdfRequest, error)
	grpc.ServerStream
}

type pdfProcessorExtractTextServer struct {
	grpc.ServerStream
}

func (x *pdfProcessorExtractTextServer) SendAndClose(m *PdfResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *pdfProcessorExtractTextServer) Recv() (*PdfRequest, error) {
	m := new(PdfRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PdfProcessor_ServiceDesc is the grpc.ServiceDesc for PdfProcessor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PdfProcessor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mcp.PdfProcessor",
	HandlerType: (*PdfProcessorServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExtractText",
			Handler:       _PdfProcessor_ExtractText_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "mcp.proto",
}
